# 站点的名称，将显示在浏览器标签页和网站顶部
site_name: Franklin Cao 的个人博客
repo_name: FranklinCao.github.io
repo_url: https://github.com/franklincao/franklincao.github.io

# 设置主题
theme:
  name: material  # 使用 Material 主题
  palette:
    primary: teal
    accent: blue

  features:
    - navigation.tabs  # 启用导航栏的选项卡布局
    - navigation.tabs.sticky  # 导航栏选项卡在页面滚动时保持固定
    - navigation.tracking  # 启用页面滚动时导航高亮当前页面所在位置
    - navigation.top  # 导航栏显示在页面顶部
    - content.code.copy  # 为代码块启用 "复制" 按钮，方便用户复制代码
    - search.highlight  # 搜索关键词在搜索结果中的文章内高亮显示

  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  search: 
    language: "zh"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franklincao


# 导航栏配置，定义网站的导航结构
nav:
  - 博客:   
    - C++:   
      - blogs/cpp/01_endianness/01_endianness.md 

# Markdown 扩展，扩展了 Markdown 的功能和语法
markdown_extensions:
  - pymdownx.highlight:  # 代码高亮扩展
      linenums: true  # 显示行号
      line_spans: __span  # 为每一行的代码块添加 span 标签，便于定制样式
      pygments_lang_class: true  # 添加语言特定的类到代码块中，便于样式定制
  - pymdownx.inlinehilite  # 启用行内代码高亮
  - pymdownx.snippets  # 允许在 Markdown 文件中插入其他文件的内容
  - pymdownx.superfences  # 启用增强的围栏代码块支持，包括多语言代码块
  - admonition  

